services:
  api:
    build:
      context: .
      dockerfile: api/hono/Dockerfile
      secrets:
        - dotenv
    env_file:
      - .env
    environment:
      - INTERNAL_API_URL=http://api:9336
    ports:
      - "9336:9336"

  web:
    build:
      context: .
      dockerfile: web/next/Dockerfile
      secrets:
        - dotenv
    env_file:
      - .env
    environment:
      - INTERNAL_API_URL=http://api:9336
    ports:
      - "9410:9410"

secrets:
  dotenv:
    file: .env
